In [1]:
import NumPy

ModuleNotFoundError: No module named 'NumPy'

In [2]:
import numpy

In [3]:
python -m pip show numpy

SyntaxError: invalid syntax (714814656.py, line 1)

In [4]:
show numpy

SyntaxError: invalid syntax (422083310.py, line 1)

In [5]:
numpy -version

NameError: name 'version' is not defined

In [7]:
import numpy as np

In [8]:
arr =  np.array([0,1,2,3,4,5,6])

In [9]:
print(arr)

[0 1 2 3 4 5 6]


In [10]:
type(arr)

numpy.ndarray

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.empty(4)

array([1., 1., 1., 1.])

In [19]:
np.ones(2,dtype = int8)

NameError: name 'int8' is not defined

In [20]:
np.ones(2,dtype = np.int8)

array([1, 1], dtype=int8)

In [22]:
ones = np.ones(shape = 3,dtype = np.int8)

In [23]:
ones

array([1, 1, 1], dtype=int8)

In [24]:
data

NameError: name 'data' is not defined

In [25]:
arr

array([0, 1, 2, 3, 4, 5, 6])

In [28]:
arr =  np.array([1,2,3])

In [29]:
arr

array([1, 2, 3])

In [30]:
arr+ones

array([2, 3, 4])

In [31]:
arr+ones+ones

array([3, 4, 5])

In [32]:
arr/1

array([1., 2., 3.])

In [36]:
arr =  np.array([1,2,3,4,5,6])

In [37]:
arr

array([1, 2, 3, 4, 5, 6])

In [38]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
arr

array([1, 2, 3, 4, 5, 6])

In [40]:
arr = arr.reshape(2,3)

In [41]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr[0][1] = 9

In [43]:
arr

array([[1, 9, 3],
       [4, 5, 6]])

## array is mutable

In [46]:
matrix = arr.reshape(3,2)

In [47]:
matrix

array([[1, 9],
       [3, 4],
       [5, 6]])

In [48]:
arr

array([[1, 9],
       [3, 4],
       [5, 6]])

In [49]:
arr*matrix

array([[ 1, 81],
       [ 9, 16],
       [25, 36]])

In [50]:
matrix[0:3,0]

array([1, 3, 5])

In [52]:
matrix[2,0:3]

array([5, 6])

In [53]:
matrix[2:]

array([[5, 6]])

In [54]:
matrix.max()

9

In [55]:
matrix.min()

1

In [56]:
matrix.sum()

28

In [58]:
matrix.min(axis = 1)

array([1, 3, 5])

In [62]:
matrix.ndim #2 dimensional array

2

In [63]:
matrix.size

6

In [64]:
matrix.shape

(3, 2)

In [66]:
num = np.array([2,5,8,94,7,3,25,0])

In [67]:
np.sort(num)

array([ 0,  2,  3,  5,  7,  8, 25, 94])

In [68]:
a = np.array([1,2,3])
b = np.array([1,2,3])

In [69]:
np.concatenate((a,b))

array([1, 2, 3, 1, 2, 3])

In [70]:
np.concatenate((a,b),axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [71]:
arr

array([[1, 9],
       [3, 4],
       [5, 6]])

In [72]:
arr.transpose()

array([[1, 3, 5],
       [9, 4, 6]])

In [73]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [74]:
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [75]:
np.arange(start = 1,stop = 11, step = 2)

array([1, 3, 5, 7, 9])

In [76]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])